fix: Avoid `sphinx` error "Code Execution failed:NameError: name 'format_locale' is not defined"
Occurs during doc build, due to both variables being used without a defintion.

```log
.\doc\Lib\site-packages\sphinxext_altair\altairplot.py:261:
UserWarning: altair-plot: .\altair\doc\user_guide/customization.rst:826 Code Execution failed:
NameError: name 'format_locale' is not defined
  warnings.warn(message, stacklevel=1)
```